import "../styles/globals.css";
import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import Providers from "@/components/Providers";
import Mainbar from "@/components/Mainbar";

const inter = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify App",
  description: "Generated by create next for spotify",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Mainbar>{children}</Mainbar>
        </Providers>
      </body>
    </html>
  );
}
